feat: Onboard census bureau international dataset
GoogleCloudPlatform/public-datasets-pipelines pull request #217
Opened 2021-10-25 19:01 UTC by nlarge-google

## Checklist

Note: Delete items below that aren't applicable to your pull request.

- [x] Please merge this PR for me once it is approved.
- [x] If this PR adds or edits a dataset or pipeline, it was reviewed and approved by the Google Cloud Public Datasets team beforehand.
- [x] If this PR adds or edits a dataset or pipeline, I put all my code inside  `datasets/census_bureau_international` and nothing outside of that directory.
- [x] This PR is appropriately labeled.

2021-11-05 19:52 UTC, adlersantos requested changes
This PR uses too many images. Try to reduce the number of images, or better yet, use a single image for seemingly related pipelines.

2021-11-29 18:21 UTC, nlarge-google commented on datasets/census_bureau_international/_images/run_csv_transform_kub_age_specific_fertility_rates/requirements.txt
> +gsutil
Done

2021-11-29 18:21 UTC, nlarge-google commented on datasets/census_bureau_international/_images/run_csv_transform_kub_country_names_area/requirements.txt
> +gsutil
Done

2021-11-29 18:21 UTC, nlarge-google commented on datasets/census_bureau_international/_images/run_csv_transform_kub_country_names_area/csv_transform.py
> +) -> None:
Done

2021-11-29 18:32 UTC, nlarge-google commented
@adlersantos Please review these changes.  Thanks, Nick.

2021-12-02 19:27 UTC, nlarge-google commented
@adlersantos I Added birth_death_growth_rates to the list of pipelines.  Please review.  Thanks!

2022-05-05 21:24 UTC, closed without merging