feat: Onboard America Health Rankings Dataset
GoogleCloudPlatform/public-datasets-pipelines pull request #244
Opened 2021-12-08 16:29 UTC by varshika06

Onboard Pipelines:

1) datasets/america_health_rankings.ahr

Based on #<ISSUE-NUMBER>

Note: It's recommended to open an issue first for context and discussion.

## Checklist

Note: Delete items below that aren't applicable to your pull request.

- [ ] Please merge this PR for me once it is approved.
- [ ] If this PR adds or edits a dataset or pipeline, it was reviewed and approved by the Google Cloud Public Datasets team beforehand.
- [ ] If this PR adds or edits a dataset or pipeline, I put all my code inside  datasets/america_health_rankings and nothing outside of that directory.
- [ ] This PR is appropriately labeled.

2021-12-17 15:34 UTC, dipannitab2392 requested changes

2021-12-17 15:34 UTC, dipannitab2392 commented on datasets/america_health_rankings/dataset.yaml
> +    description: "America Health Rankings"
please add location here

`
- type: storage_bucket
    name: <dataset-name>
    uniform_bucket_level_access: True
    location: US
`

2021-12-20 14:40 UTC, varshika06 commented on datasets/america_health_rankings/dataset.yaml
> +    description: "America Health Rankings"
Done.

2021-12-21 19:59 UTC, adlersantos approved these changes
Good work @varshika06. Thanks @dipannitab2392 for reviewing!

2021-12-21 19:59 UTC, merged