Feat: Onboard EPA dataset
GoogleCloudPlatform/public-datasets-pipelines pull request #301
Opened 2022-02-25 20:57 UTC by nlarge-google

## Description

* Dataset now utilizes individual clusters in order to resolve resource failures when running on the main cluster

## Checklist

Note: If an item applies to you, all of its sub-items must be fulfilled

- [ ] **(Required)** This pull request is appropriately labeled
- [ ] Please merge this pull request after it's approved
- [ ] I'm adding or editing a feature
  - [ ] I have added tests for the feature
- [ ] I'm adding or editing a dataset
  - [ ] The [Google Cloud Datasets team](mailto:cloud-datasets-onboarding@google.com) is aware of the proposed dataset
  - [ ] I put all my code inside  `datasets/epa_historical_air_quality` and nothing outside of that directory
- [ ] I'm submitting a bugfix
- [ ] I'm refactoring or cleaning up some code

2022-02-25 21:06 UTC, nlarge-google commented
@adlersantos Please review these changes

2022-03-03 13:48 UTC, nlarge-google commented
@adlersantos @happyhuman Please review the code changes.  The system now implements the new folder structure along with utilizing a cluster create and other changes to improve code.

2022-03-21 17:10 UTC, adlersantos requested changes
Let's merge these multiple DAGs into one that creates and deletes a single cluster

2022-04-04 17:06 UTC, adlersantos commented on datasets/epa_historical_air_quality/pipelines/hap_daily_summary/pipeline.yaml
> -    description: "epaspc"
After generating the TF files, you should have very few files under the `infra` folder.

2022-04-08 19:36 UTC, nlarge-google commented on datasets/epa_historical_air_quality/pipelines/hap_daily_summary/pipeline.yaml
> -    description: "epaspc"
Done

2022-04-08 19:37 UTC, nlarge-google commented
@adlersantos @happyhuman Please review following latest changes.  Thanks!

2022-04-08 20:12 UTC, adlersantos approved these changes

2022-04-08 20:12 UTC, merged