Feat: Onboard Census Bureau ACS Dataset
GoogleCloudPlatform/public-datasets-pipelines pull request #399
Opened 2022-07-04 10:37 UTC by Naveen130

## Description

Pipelines included:

- cbsa_2019_1yr
- cbsa_2020_1yr
- cbsa_2021_1yr
- cbsa_2019_5yr
- cbsa_2020_5yr
- cbsa_2021_5yr
- censustract_2019_5yr
- censustract_2020_5yr
- censustract_2021_5yr
- congressionaldistrict_2019_1yr
- congressionaldistrict_2020_1yr
- congressionaldistrict_2021_1yr
- congressionaldistrict_2019_5yr
- congressionaldistrict_2020_5yr
- congressionaldistrict_2021_5yr
- county_2019_1yr
- county_2020_1yr
- county_2021_1yr
- county_2019_5yr
- county_2020_5yr
- county_2021_5yr
- place_2019_1yr
- place_2020_1yr
- place_2021_1yr
- place_2019_5yr
- place_2020_5yr
- place_2021_5yr
- puma_2019_1yr
- puma_2020_1yr
- puma_2021_1yr
- puma_2019_5yr
- puma_2020_5yr
- puma_2021_5yr
- schooldistrictelementary_2016_1yr
- schooldistrictelementary_2017_1yr
- schooldistrictelementary_2018_1yr
- schooldistrictelementary_2019_1yr
- schooldistrictelementary_2020_1yr
- schooldistrictelementary_2021_1yr
- schooldistrictelementary_2016_5yr
- schooldistrictelementary_2017_5yr
- schooldistrictelementary_2018_5yr
- schooldistrictelementary_2019_5yr
- schooldistrictelementary_2020_5yr
- schooldistrictelementary_2021_5yr
- schooldistrictsecondary_2016_1yr
- schooldistrictsecondary_2017_1yr
- schooldistrictsecondary_2018_1yr
- schooldistrictsecondary_2019_1yr
- schooldistrictsecondary_2020_1yr
- schooldistrictsecondary_2021_1yr
- schooldistrictsecondary_2016_5yr
- schooldistrictsecondary_2017_5yr
- schooldistrictsecondary_2018_5yr
- schooldistrictsecondary_2019_5yr
- schooldistrictsecondary_2020_5yr
- schooldistrictsecondary_2021_5yr
- schooldistrictunified_2016_1yr
- schooldistrictunified_2017_1yr
- schooldistrictunified_2018_1yr
- schooldistrictunified_2019_1yr
- schooldistrictunified_2020_1yr
- schooldistrictunified_2021_1yr
- schooldistrictunified_2016_5yr
- schooldistrictunified_2017_5yr
- schooldistrictunified_2018_5yr
- schooldistrictunified_2019_5yr
- schooldistrictunified_2020_5yr
- schooldistrictunified_2021_5yr
- state_2019_1yr
- state_2020_1yr
- state_2021_1yr
- state_2019_5yr
- state_2020_5yr
- state_2021_5yr
- zcta_2019_5yr
- zcta_2020_5yr
- zcta_2021_5yr
## Checklist

Note: If an item applies to you, all of its sub-items must be fulfilled

- [ ] **(Required)** This pull request is appropriately labeled
- [ ] Please merge this pull request after it's approved
- [ ] I'm adding or editing a dataset
  - [ ] The [Google Cloud Datasets team](mailto:cloud-datasets-onboarding@google.com) is aware of the proposed dataset
  - [ ] I put all my code inside  `datasets/<DATASET_NAME>` and nothing outside of that directory
- [ ] I'm refactoring or cleaning up some code

2022-07-07 18:20 UTC, nlarge-google commented on datasets/census_bureau_acs/pipelines/_images/run_csv_transform_kub/csv_transform.py
> +
remove unnecessary blank lines within functions

2022-07-08 16:53 UTC, Naveen130 commented
Sure, will take care of the extra blank lines and comments.

2022-07-08 18:43 UTC, nlarge-google requested changes
Still some lines that were missed.

2022-07-08 18:43 UTC, nlarge-google commented on datasets/census_bureau_acs/pipelines/_images/run_csv_transform_kub/csv_transform.py
> +
Here

2022-07-08 18:43 UTC, nlarge-google commented on datasets/census_bureau_acs/pipelines/_images/run_csv_transform_kub/csv_transform.py
Here

2022-07-08 18:43 UTC, nlarge-google commented on datasets/census_bureau_acs/pipelines/_images/run_csv_transform_kub/csv_transform.py
Here

2022-07-08 18:43 UTC, nlarge-google commented on datasets/census_bureau_acs/pipelines/_images/run_csv_transform_kub/csv_transform.py
> +
Here

2022-07-08 18:43 UTC, nlarge-google commented on datasets/census_bureau_acs/pipelines/_images/run_csv_transform_kub/csv_transform.py
> +
Here

2022-07-08 18:43 UTC, nlarge-google commented on datasets/census_bureau_acs/pipelines/_images/run_csv_transform_kub/csv_transform.py
> +
Here

2022-07-08 19:44 UTC, Naveen130 commented on datasets/census_bureau_acs/pipelines/_images/run_csv_transform_kub/csv_transform.py
> +    # set_df_datatypes(df, data_dtypes)
Done

2022-07-08 19:44 UTC, Naveen130 commented on datasets/census_bureau_acs/pipelines/_images/run_csv_transform_kub/csv_transform.py
> +
Done

2022-07-08 19:44 UTC, Naveen130 commented on datasets/census_bureau_acs/pipelines/_images/run_csv_transform_kub/csv_transform.py
Done

2022-07-08 19:44 UTC, Naveen130 commented on datasets/census_bureau_acs/pipelines/_images/run_csv_transform_kub/csv_transform.py
Done

2022-07-08 19:44 UTC, Naveen130 commented on datasets/census_bureau_acs/pipelines/_images/run_csv_transform_kub/csv_transform.py
> +
Done

2022-07-08 19:45 UTC, Naveen130 commented on datasets/census_bureau_acs/pipelines/_images/run_csv_transform_kub/csv_transform.py
> +
Done

2022-07-08 19:45 UTC, Naveen130 commented on datasets/census_bureau_acs/pipelines/_images/run_csv_transform_kub/csv_transform.py
> +
Done

2022-07-08 22:01 UTC, nlarge-google approved these changes
Looks Great.

2022-07-08 22:01 UTC, merged