Feat: Onboard Uniref50 dataset
GoogleCloudPlatform/public-datasets-pipelines pull request #443
Opened 2022-08-12 19:34 UTC by gkodukula

## Description

Dataset: Uniref50

## Checklist

- [ ] **(Required)** This pull request is appropriately labeled
- [ ] Please merge this pull request after it's approved

Use the sections below based on what's applicable to your PR and delete the rest:

### Feature
- [ ] I'm adding or editing a feature
- [ ] I have updated the [`README`](https://github.com/GoogleCloudPlatform/public-datasets-pipelines/blob/main/README.md) accordingly
- [ ] I have added/revised tests for the feature

### Data Onboarding
- [ ] I'm adding or editing a dataset
- [ ] The [Google Cloud Datasets team](mailto:cloud-datasets-onboarding@google.com) is aware of the proposed dataset
- [ ] I put all my code inside  `datasets/<Uniref50>` and nothing outside of that directory

2022-08-22 16:15 UTC, gkodukula commented
@nlarge-google can you please review this code

2022-08-25 03:11 UTC, nlarge-google requested changes

2022-08-25 03:11 UTC, nlarge-google commented on datasets/uniref50/pipelines/_images/run_csv_transform_kub/csv_transform.py
> +
Please remove extra lines

2022-08-25 03:11 UTC, nlarge-google commented on datasets/uniref50/pipelines/_images/run_csv_transform_kub/csv_transform.py
> +
Please remove extra lines

2022-08-25 17:24 UTC, gkodukula commented on datasets/uniref50/pipelines/_images/run_csv_transform_kub/csv_transform.py
> +
done @nlarge-google

2022-08-25 17:24 UTC, gkodukula commented on datasets/uniref50/pipelines/_images/run_csv_transform_kub/csv_transform.py
> +
done @nlarge-google

2022-08-29 15:20 UTC, nlarge-google approved these changes

2022-08-29 15:20 UTC, merged