Feat: Onboard Mimiciii dataset
GoogleCloudPlatform/public-datasets-pipelines pull request #449
Opened 2022-08-17 14:40 UTC by Naveen130

## Description

This is to onboard mimiciii dataset with 25 pipelines using Airflow v2 operators only.

## Checklist

- [ ] **(Required)** This pull request is appropriately labeled
- [ ] Please merge this pull request after it's approved

Use the sections below based on what's applicable to your PR and delete the rest:

### Feature
- [ ] I'm adding or editing a feature
- [ ] I have updated the [`README`](https://github.com/GoogleCloudPlatform/public-datasets-pipelines/blob/main/README.md) accordingly
- [ ] I have added/revised tests for the feature

### Data Onboarding
- [ ] I'm adding or editing a dataset
- [ ] The [Google Cloud Datasets team](mailto:cloud-datasets-onboarding@google.com) is aware of the proposed dataset
- [ ] I put all my code inside  `datasets/mimiciii` and nothing outside of that directory

### Code cleanup or refactoring
- [ ] I'm refactoring or cleaning up some code

2022-08-17 15:21 UTC, Naveen130 commented
This PR includes 2 activities w.r.t. the dataset -
1. Removes mimicIII (uses Airflow v1 operator, not acceptable anymore)
2. Adds mimiciii (uses accepted Airflow v2 operator)

2022-08-17 15:39 UTC, adlersantos commented
Use the BQ data transfer service. There are examples in the repo that you can just reuse:
https://github.com/GoogleCloudPlatform/public-datasets-pipelines/tree/main/datasets/scalable_open_source/pipelines/_images/bq_data_transfer

2022-08-17 15:39 UTC, adlersantos commented
Also, please rename to mimic_iii

2022-08-17 15:43 UTC, adlersantos requested changes
Please use BQ data transfer and rename to mimic_iii

2022-08-25 03:08 UTC, nlarge-google requested changes
Please remove extra lines

2022-08-25 03:08 UTC, nlarge-google commented on datasets/mimiciii/pipelines/_images/run_csv_transform_kub/csv_transform.py
> +
Please remove extra lines

2022-08-25 09:27 UTC, closed without merging