Feat : Onboard NHTSA Traffic Fatalities Dataset
GoogleCloudPlatform/public-datasets-pipelines pull request #454
Opened 2022-08-22 15:58 UTC by aurogoogle

## Description

Dataset: NHTSA Traffic Fatalities

## Checklist

- [ ] **(Required)** This pull request is appropriately labeled
- [ ] Please merge this pull request after it's approved

Use the sections below based on what's applicable to your PR and delete the rest:

### Feature
- [ ] I'm adding or editing a feature
- [ ] I have updated the [`README`](https://github.com/GoogleCloudPlatform/public-datasets-pipelines/blob/main/README.md) accordingly

### Data Onboarding
- [ ] I'm adding or editing a dataset
- [ ] The [Google Cloud Datasets team](mailto:cloud-datasets-onboarding@google.com) is aware of the proposed dataset
- [ ] I put all my code inside  `datasets/<nhtsa_traffic_fatalities>` and nothing outside of that directory

2022-08-22 17:42 UTC, aurogoogle commented
@adlersantos @nlarge-google Kindly review.

2022-08-25 03:03 UTC, nlarge-google requested changes
Great Job, just removal of blank lines.

2022-08-25 03:03 UTC, nlarge-google commented on datasets/nhtsa_traffic_fatalities/pipelines/_images/run_csv_transform_kub/csv_transform.py
> +
Please remove extra lines

2022-08-25 03:03 UTC, nlarge-google commented on datasets/nhtsa_traffic_fatalities/pipelines/_images/run_csv_transform_kub/csv_transform.py
> +
Please remove extra lines

2022-08-25 13:27 UTC, aurogoogle commented on Pipfile
> +
Removed the mentioned file from the commit / branch.

2022-08-25 13:27 UTC, aurogoogle commented on Pipfile.lock
> +{
Removed the mentioned file from the commit / branch.

2022-08-25 13:27 UTC, aurogoogle commented on datasets/nhtsa_traffic_fatalities/pipelines/_images/run_csv_transform_kub/csv_transform.py
> +
Removed extra spaces.

2022-08-25 13:27 UTC, aurogoogle commented on datasets/nhtsa_traffic_fatalities/pipelines/_images/run_csv_transform_kub/csv_transform.py
> +
Removed extra spaces.

2022-08-25 13:28 UTC, aurogoogle commented
Hey @nlarge-google I have addressed the mentioned changes. Kindly review.

2022-08-25 15:10 UTC, nlarge-google approved these changes

2022-08-25 15:10 UTC, nlarge-google commented
Great Job!

2022-08-25 15:11 UTC, merged