Feat: Onboard dataset Mimic-III
GoogleCloudPlatform/public-datasets-pipelines pull request #456
Opened 2022-08-23 15:10 UTC by Naveen130

## Description

This dataset includes 25 pipelines.

## Checklist

- [ ] **(Required)** This pull request is appropriately labeled
- [ ] Please merge this pull request after it's approved

Use the sections below based on what's applicable to your PR and delete the rest:

### Data Onboarding
- [ ] I'm adding or editing a dataset
- [ ] The [Google Cloud Datasets team](mailto:cloud-datasets-onboarding@google.com) is aware of the proposed dataset
- [ ] I put all my code inside  `datasets/<DATASET_NAME>` and nothing outside of that directory

### Code cleanup or refactoring
- [ ] I'm refactoring or cleaning up some code

2022-08-23 15:20 UTC, Naveen130 commented
This pull request is to delete the existing dataset named mimicIII and add the dataset mimic_iii

2022-08-23 15:37 UTC, Naveen130 commented
Please review @adlersantos @nlarge-google

2022-08-25 02:57 UTC, nlarge-google requested changes
Great job - just please remove blank lines and we should be good.  Thanks.

2022-08-25 02:57 UTC, nlarge-google commented on datasets/mimic_iii/pipelines/_images/run_script_kub/script.py
> +
please remove blank lines in functions

2022-08-25 02:57 UTC, nlarge-google commented on datasets/mimicIII/pipelines/mimicIII/pipeline.yaml
> -
Please remove blank lines between operators

2022-11-08 21:18 UTC, adlersantos approved these changes

2022-11-08 22:16 UTC, nlarge-google approved these changes
Great Job Naveen!

2022-11-08 22:16 UTC, merged