Feat: Migrate the World Bank datasets x 3 from Xenon
GoogleCloudPlatform/public-datasets-pipelines pull request #506
Opened 2022-10-10 11:24 UTC by Naveen130

## Description

This PR makes changes to these 3 existing datasets 
- world_bank_health_population
- world_bank_intl_debt
- world_bank_intl_education

## Checklist

- [x] **(Required)** This pull request is appropriately labeled
- [x] Please merge this pull request after it's approved

### Code cleanup or refactoring
- [x] I'm refactoring or cleaning up some code

2022-10-10 11:31 UTC, Naveen130 commented
@nlarge-google As discussed, I have made the changes in a single PR for the remaining World Bank datasets.

2022-10-10 19:28 UTC, nlarge-google requested changes
Some changes necessary.  Great job though!

2022-10-10 19:28 UTC, nlarge-google commented on datasets/world_bank_health_population/pipelines/_images/run_csv_transform_kub/csv_transform.py
Remove blank line

2022-10-10 19:28 UTC, nlarge-google commented on datasets/world_bank_health_population/pipelines/_images/run_csv_transform_kub/csv_transform.py
> +        # logging.info("Transform: Creating a new column ...")
Remove remarked-out code

2022-10-10 19:28 UTC, nlarge-google commented on datasets/world_bank_health_population/pipelines/_images/run_csv_transform_kub/csv_transform.py
>      logging.info(f"Saving to output file.. {target_file}")
Move logging to function definition

2022-10-10 19:28 UTC, nlarge-google commented on datasets/world_bank_health_population/pipelines/_images/run_csv_transform_kub/csv_transform.py
>      logging.info(f"Downloading file {source_url}")
Move logging to function definition

2022-10-10 19:28 UTC, nlarge-google commented on datasets/world_bank_health_population/pipelines/_images/run_csv_transform_kub/csv_transform.py
>      logging.info(f"Transforming {source_file} ... ")
Remove this line

2022-10-10 19:28 UTC, nlarge-google commented on datasets/world_bank_health_population/pipelines/_images/run_csv_transform_kub/csv_transform.py
>      logging.info(f"Transform: Renaming columns for {pipeline_name} ...")
Move logging to function definition

2022-10-10 19:28 UTC, nlarge-google commented on datasets/world_bank_health_population/pipelines/_images/run_csv_transform_kub/csv_transform.py
>          df = df
replace "df = df" with "pass"

2022-10-10 19:28 UTC, nlarge-google commented on datasets/world_bank_health_population/pipelines/_images/run_csv_transform_kub/csv_transform.py
>      logging.info(
Move logging to function definition

2022-10-17 19:19 UTC, nlarge-google approved these changes
Approved.

2022-10-17 19:20 UTC, merged