feat: add Iowa liquor sales samples for Vertex AI Forecasting tutorial
GoogleCloudPlatform/public-datasets-pipelines pull request #85
Opened 2021-06-11 21:28 UTC by thehardikv

## Description

Adding samples of the Iowa liquor sales dataset to create a BQ Vertex AI Forecasting tutorial.

## Checklist

- [x] Please merge this PR for me once it is approved.
- [ ] If this PR adds or edits a feature, I have updated the [`README`](https://github.com/GoogleCloudPlatform/public-datasets-pipelines/blob/main/README.md) accordingly.
- [x] If this PR adds or edits a dataset or pipeline, it was reviewed and approved by the Google Cloud Public Datasets team beforehand.
- [x] If this PR adds or edits a dataset or pipeline, I put all my code inside  `datasets/<YOUR-DATASET>` and nothing outside of that directory.
- [x] If this PR adds or edits a dataset or pipeline that I'm responsible for maintaining, my GitHub username is in the [`CONTRIBUTORS` file](https://github.com/GoogleCloudPlatform/public-datasets-pipelines/blob/main/CONTRIBUTORS).
- [ ] This PR is appropriately labeled.

2021-06-11 22:09 UTC, adlersantos requested changes
Just a few simple changes and we're good to go.

Please regenerate the Terraform and DAG files after the YAML revisions. Thanks!

2021-06-11 22:09 UTC, adlersantos commented on datasets/iowa_liquor_sales/dataset.yaml
> +    description: "A time series dataset containing samples drawn from the Iowa Liquor Retail Sales dataset. Data were made available by the Iowa Department of Commerce. It is provided under the Creat
Please use `console.cloud.google.com` over `pantheon.corp.google.com`

2021-06-11 22:09 UTC, adlersantos commented on datasets/iowa_liquor_sales/dataset.yaml
> +    dataset_id: iowa_liquor_sales
I think your target dataset is `iowa_liquor_sales_forecasting` (and not `iowa_liquor_sales`)? Let's provision that resource over this one.

2021-06-14 18:08 UTC, thehardikv commented on datasets/iowa_liquor_sales/dataset.yaml
> +    description: "A time series dataset containing samples drawn from the Iowa Liquor Retail Sales dataset. Data were made available by the Iowa Department of Commerce. It is provided under the Creat
Done.

2021-06-14 19:11 UTC, adlersantos approved these changes

2021-06-14 19:11 UTC, merged